config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :credit_cards
  resources :products
  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: %i[ show edit update destroy ]

  # GET /credit_cards or /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1 or /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards or /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)
    @credit_card.user_id = current_user.id

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to credit_card_url(@credit_card), notice: "Credit card was successfully created." }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1 or /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to credit_card_url(@credit_card), notice: "Credit card was successfully updated." }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1 or /credit_cards/1.json
  def destroy
    @credit_card.destroy

    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: "Credit card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_card_params
      params.require(:credit_card).permit(:id, :name, :card_number, :expiration_date, :cvv, :user_id, :created_at, :updated_at)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_credit_card.html.erb
<div id="<%= dom_id credit_card %>">
  <p>
    <strong>Id:</strong>
    <%= credit_card.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= credit_card.name %>
  </p>

  <p>
    <strong>Card number string:</strong>
    <%= credit_card.card_number_string %>
  </p>

  <p>
    <strong>Expiration date:</strong>
    <%= credit_card.expiration_date %>
  </p>

  <p>
    <strong>Cvv:</strong>
    <%= credit_card.cvv %>
  </p>

  <p>
    <strong>User:</strong>
    <%= credit_card.user_id %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= credit_card.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= credit_card.updated_at %>
  </p>

</div>

app/views/credit_cards/_form.html.erb
<%= form_with(model: credit_card) do |form| %>
  <% if credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
        <% credit_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_field :card_number %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= form.label :cvv %>
    <%= form.text_field :cvv %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit card</h1>

<%= render "form", credit_card: @credit_card %>

<br>

<div>
  <%= link_to "Show this credit card", @credit_card %> |
  <%= link_to "Back to credit cards", credit_cards_path %>
</div>

app/views/credit_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Credit cards</h1>

<div id="credit_cards">
  <% @credit_cards.each do |credit_card| %>
    <%= render credit_card %>
    <p>
      <%= link_to "Show this credit card", credit_card %>
    </p>
  <% end %>
</div>

<%= link_to "New credit card", new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New credit card</h1>

<%= render "form", credit_card: @credit_card %>

<br>

<div>
  <%= link_to "Back to credit cards", credit_cards_path %>
</div>

app/views/credit_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @credit_card %>

<div>
  <%= link_to "Edit this credit card", edit_credit_card_path(@credit_card) %> |
  <%= link_to "Back to credit cards", credit_cards_path %>

  <%= button_to "Destroy this credit card", @credit_card, method: :delete %>
</div>