config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :credit_cards
  resources :products
  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    if current_user.id != nil
      @transactions = Transaction.where(user_id: current_user.id)
    else
      @transactions = Transaction.all
    end
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    # We add these lines so that the selected product’s data fields and user’s credit cards are available to the views at the front end
    if @product.nil?
      @product = Product.find(params[:product_id])
    end
    @credit_cards = current_user.credit_cards
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction = Transaction.new(transaction_params)
    @transaction.transaction_number = Array.new(10){[*"A".."Z", *"0".."9"].sample}.join
    @product = Product.find(params[:transaction][:product_id])
    @transaction.user_id = current_user.id
    @product.quantity = @product.quantity - @transaction.quantity
    @product.save
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:quantity, :total_cost, :product_id, :credit_card_id)

    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>You are purchasing the product: <%= @product.name %></p>

  <div class="field">
    <% qty = @product.quantity %>
    <%= form.label :quantity %>
    <%= form.number_field :quantity, :id => 'quantity', min: 1, max: qty, onchange: "calculateTotalPrice();" %>
  </div>

  <div class="field">
    <%= form.label :total_cost %>
    <%= form.text_field :total_cost, :id => 'total_cost', :readonly => true %>
  </div>

  <div class="field">
    <%= form.hidden_field :product_id, value: @product.id %>
  </div>

  <div class="field">
    <%= form.label :credit_card_id, "Credit card number" %>
    <%= form.collection_select :credit_card_id, CreditCard.where(user_id: current_user.id),:id,:card_number, include_blank: false %>
  </div>


  <div class="actions">
    <%= form.submit "complete" %>
  </div>

<% end %>

<script type="text/javascript">
    function calculateTotalPrice() {
        var price = "<%= @product.price %>";
        document.getElementById('total_cost').value = document.getElementById('quantity').value * price;
    }
</script>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Transaction number:</strong>
    <%= transaction.transaction_number %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= transaction.quantity %>
  </p>

  <p>
    <strong>Total cost:</strong>
    <%= transaction.total_cost %>
  </p>

  <p>
    <strong>User:</strong>
    <%= transaction.user_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= transaction.product_id %>
  </p>

  <p>
    <strong>Creditcard:</strong>
    <%= transaction.creditcard_id %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= transaction.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= transaction.updated_at %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction number:</strong>
  <%= @transaction.transaction_number %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @transaction.total_cost %>
</p>

<%# link_to 'Edit', edit_transaction_path(@transaction) %>
<%= link_to 'Back', transactions_path %>